sonar.projectKey=custodia
sonar.projectName=Custodia
sonar.sources=src/
sonar.tests=tests/
sonar.exclusions=**/bin/**,**/obj/**,**/Migrations/**
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.host.url=http://localhost:9000
